package net.xinqushi.common.enums;
/**
 * 操作类型枚举
 * @author yangli
 */
public enum OperationType {

	USER_REGISTER, // 0
	USER_LOGIN,  // 1
	USER_UPDATE_PHONE, // 2 
	PLACE_RESERVATION, // 3
	QRCODE_RESERVATION, // 4
	USE_COUPON, // 5
	CANCEL_RESERVATION, // 6
	RATING_RESERVATION, // 7
	ADD_CAR, //8
	UPDATE_CAR, // 9
	DELETE_CAR, // 10
	CAR_ONLINE, // 11
	CAR_OFFLINE, // 12
	QRCODE_ORDER, // 13
	SEARCH_RESERVATION, // 14 
	ADD_RESERVATION_TO_ORDER, // 15
	CANCEL_ORDER, // 16
	REMOVE_RESERVATION_FROM_ORDER, // 17 
	START_ORDER, // 18
	FINISH_ORDER, // 19
	PAYMENT_LOG, // 20
	SEND_SMS, // 21
	START_REFUND, // 22
	CANCEL_REFUND, // 23
	CAR_AUDIT, // 24  车辆审核
	CH_FINISHED,//25

	CH_NEED_REFUND,//
	CH_DEPARTURE,
	CANCEL_TELERESERV_DISPATCHER, // 28 取消电话订单
	TELERESERV_INPUT, // 29 电话订单录入
	RESERV_MARK_ISTAKEN, // 30 确认订单
	WAITING_PASSENGER, // 31 开始等待
	START_RESERVATION, // 32 订单开始
	DRIVER_ONLINE, // 33 司机登陆
	CAR_LOGIN, // 34 车辆登陆
	DRIVER_OFFLINE, // 35 司机下线
	GEN_RENTAL_BILL, // 36 生成租车账单
	ADD_RENTAL_CAR, //37 新增车辆
	DEL_DRIVER, //38 删除司机
	GOV_RESERV_INPUT, //39 录入政企订单
	MAN_UPDATE_RESERV, //40 后台操作修改订单
	MAN_UPDATE_ORDER, //41 后台操作修改司机行程
	
	PAYMENT_PREPAY, //42 预支付
	GOV_RESERV_LOGCONFIRMPRICE, //43记录政企订单核价
	TEST_OPERATION //44测试用

}
