package net.xinqushi.orm.entity;

import net.xinqushi.common.enums.OperationType;

public class AuditLog {
    private Long id;

    private OperationType opType;
    
    private OperationType opTypeStr;

    private Long time;

    private Long userId;

    private String phone;

    private String deviceId;

    private String version;
    
    private Integer managementUserId;
    
    private String managementUserName;
    
    /** 新增loginName*/
    private String managementLoginName;

    private Long reservId;

    private String reservNo;

    private Long orderId;

    private String orderNo;

    private String strField1;

    private String strField2;

    private String strField3;

    private String strField4;

    private Integer intField1;

    private Integer intField2;

    private Integer intField3;

    private Integer intField4;

    private Float floatField1;

    private Float floatField2;

    private Float floatField3;

    private Float floatField4;

    private Double doubleField1;

    private Double doubleField2;

    private Double doubleField3;

    private Double doubleField4;

    private Long longField1;

    private Long longField2;

    private Long longField3;

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public OperationType getOpType() {
        return opType;
    }

    public void setOpType(OperationType opType) {
        this.opType = opType;
    }

    public Long getTime() {
        return time;
    }

    public void setTime(Long time) {
        this.time = time;
    }

    public Long getUserId() {
        return userId;
    }

    public void setUserId(Long userId) {
        this.userId = userId;
    }

    public String getPhone() {
        return phone;
    }

    public void setPhone(String phone) {
        this.phone = phone == null ? null : phone.trim();
    }

    public String getDeviceId() {
        return deviceId;
    }

    public void setDeviceId(String deviceId) {
        this.deviceId = deviceId == null ? null : deviceId.trim();
    }

    public String getVersion() {
        return version;
    }

    public void setVersion(String version) {
        this.version = version == null ? null : version.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_audit_log.reservId
     *
     * @return the value of tbl_audit_log.reservId
     *
     * @mbggenerated Sat Jan 30 17:19:35 CST 2016
     */
    public Long getReservId() {
        return reservId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_audit_log.reservId
     *
     * @param reservId the value for tbl_audit_log.reservId
     *
     * @mbggenerated Sat Jan 30 17:19:35 CST 2016
     */
    public void setReservId(Long reservId) {
        this.reservId = reservId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_audit_log.reservNo
     *
     * @return the value of tbl_audit_log.reservNo
     *
     * @mbggenerated Sat Jan 30 17:19:35 CST 2016
     */
    public String getReservNo() {
        return reservNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_audit_log.reservNo
     *
     * @param reservNo the value for tbl_audit_log.reservNo
     *
     * @mbggenerated Sat Jan 30 17:19:35 CST 2016
     */
    public void setReservNo(String reservNo) {
        this.reservNo = reservNo == null ? null : reservNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_audit_log.orderId
     *
     * @return the value of tbl_audit_log.orderId
     *
     * @mbggenerated Sat Jan 30 17:19:35 CST 2016
     */
    public Long getOrderId() {
        return orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_audit_log.orderId
     *
     * @param orderId the value for tbl_audit_log.orderId
     *
     * @mbggenerated Sat Jan 30 17:19:35 CST 2016
     */
    public void setOrderId(Long orderId) {
        this.orderId = orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_audit_log.orderNo
     *
     * @return the value of tbl_audit_log.orderNo
     *
     * @mbggenerated Sat Jan 30 17:19:35 CST 2016
     */
    public String getOrderNo() {
        return orderNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_audit_log.orderNo
     *
     * @param orderNo the value for tbl_audit_log.orderNo
     *
     * @mbggenerated Sat Jan 30 17:19:35 CST 2016
     */
    public void setOrderNo(String orderNo) {
        this.orderNo = orderNo == null ? null : orderNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_audit_log.strField1
     *
     * @return the value of tbl_audit_log.strField1
     *
     * @mbggenerated Sat Jan 30 17:19:35 CST 2016
     */
    public String getStrField1() {
        return strField1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_audit_log.strField1
     *
     * @param strField1 the value for tbl_audit_log.strField1
     *
     * @mbggenerated Sat Jan 30 17:19:35 CST 2016
     */
    public void setStrField1(String strField1) {
        this.strField1 = strField1 == null ? null : strField1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_audit_log.strField2
     *
     * @return the value of tbl_audit_log.strField2
     *
     * @mbggenerated Sat Jan 30 17:19:35 CST 2016
     */
    public String getStrField2() {
        return strField2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_audit_log.strField2
     *
     * @param strField2 the value for tbl_audit_log.strField2
     *
     * @mbggenerated Sat Jan 30 17:19:35 CST 2016
     */
    public void setStrField2(String strField2) {
        this.strField2 = strField2 == null ? null : strField2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_audit_log.strField3
     *
     * @return the value of tbl_audit_log.strField3
     *
     * @mbggenerated Sat Jan 30 17:19:35 CST 2016
     */
    public String getStrField3() {
        return strField3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_audit_log.strField3
     *
     * @param strField3 the value for tbl_audit_log.strField3
     *
     * @mbggenerated Sat Jan 30 17:19:35 CST 2016
     */
    public void setStrField3(String strField3) {
        this.strField3 = strField3 == null ? null : strField3.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_audit_log.strField4
     *
     * @return the value of tbl_audit_log.strField4
     *
     * @mbggenerated Sat Jan 30 17:19:35 CST 2016
     */
    public String getStrField4() {
        return strField4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_audit_log.strField4
     *
     * @param strField4 the value for tbl_audit_log.strField4
     *
     * @mbggenerated Sat Jan 30 17:19:35 CST 2016
     */
    public void setStrField4(String strField4) {
        this.strField4 = strField4 == null ? null : strField4.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_audit_log.intField1
     *
     * @return the value of tbl_audit_log.intField1
     *
     * @mbggenerated Sat Jan 30 17:19:35 CST 2016
     */
    public Integer getIntField1() {
        return intField1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_audit_log.intField1
     *
     * @param intField1 the value for tbl_audit_log.intField1
     *
     * @mbggenerated Sat Jan 30 17:19:35 CST 2016
     */
    public void setIntField1(Integer intField1) {
        this.intField1 = intField1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_audit_log.intField2
     *
     * @return the value of tbl_audit_log.intField2
     *
     * @mbggenerated Sat Jan 30 17:19:35 CST 2016
     */
    public Integer getIntField2() {
        return intField2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_audit_log.intField2
     *
     * @param intField2 the value for tbl_audit_log.intField2
     *
     * @mbggenerated Sat Jan 30 17:19:35 CST 2016
     */
    public void setIntField2(Integer intField2) {
        this.intField2 = intField2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_audit_log.intField3
     *
     * @return the value of tbl_audit_log.intField3
     *
     * @mbggenerated Sat Jan 30 17:19:35 CST 2016
     */
    public Integer getIntField3() {
        return intField3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_audit_log.intField3
     *
     * @param intField3 the value for tbl_audit_log.intField3
     *
     * @mbggenerated Sat Jan 30 17:19:35 CST 2016
     */
    public void setIntField3(Integer intField3) {
        this.intField3 = intField3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_audit_log.intField4
     *
     * @return the value of tbl_audit_log.intField4
     *
     * @mbggenerated Sat Jan 30 17:19:35 CST 2016
     */
    public Integer getIntField4() {
        return intField4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_audit_log.intField4
     *
     * @param intField4 the value for tbl_audit_log.intField4
     *
     * @mbggenerated Sat Jan 30 17:19:35 CST 2016
     */
    public void setIntField4(Integer intField4) {
        this.intField4 = intField4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_audit_log.floatField1
     *
     * @return the value of tbl_audit_log.floatField1
     *
     * @mbggenerated Sat Jan 30 17:19:35 CST 2016
     */
    public Float getFloatField1() {
        return floatField1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_audit_log.floatField1
     *
     * @param floatField1 the value for tbl_audit_log.floatField1
     *
     * @mbggenerated Sat Jan 30 17:19:35 CST 2016
     */
    public void setFloatField1(Float floatField1) {
        this.floatField1 = floatField1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_audit_log.floatField2
     *
     * @return the value of tbl_audit_log.floatField2
     *
     * @mbggenerated Sat Jan 30 17:19:35 CST 2016
     */
    public Float getFloatField2() {
        return floatField2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_audit_log.floatField2
     *
     * @param floatField2 the value for tbl_audit_log.floatField2
     *
     * @mbggenerated Sat Jan 30 17:19:35 CST 2016
     */
    public void setFloatField2(Float floatField2) {
        this.floatField2 = floatField2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_audit_log.floatField3
     *
     * @return the value of tbl_audit_log.floatField3
     *
     * @mbggenerated Sat Jan 30 17:19:35 CST 2016
     */
    public Float getFloatField3() {
        return floatField3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_audit_log.floatField3
     *
     * @param floatField3 the value for tbl_audit_log.floatField3
     *
     * @mbggenerated Sat Jan 30 17:19:35 CST 2016
     */
    public void setFloatField3(Float floatField3) {
        this.floatField3 = floatField3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_audit_log.floatField4
     *
     * @return the value of tbl_audit_log.floatField4
     *
     * @mbggenerated Sat Jan 30 17:19:35 CST 2016
     */
    public Float getFloatField4() {
        return floatField4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_audit_log.floatField4
     *
     * @param floatField4 the value for tbl_audit_log.floatField4
     *
     * @mbggenerated Sat Jan 30 17:19:35 CST 2016
     */
    public void setFloatField4(Float floatField4) {
        this.floatField4 = floatField4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_audit_log.doubleField1
     *
     * @return the value of tbl_audit_log.doubleField1
     *
     * @mbggenerated Sat Jan 30 17:19:35 CST 2016
     */
    public Double getDoubleField1() {
        return doubleField1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_audit_log.doubleField1
     *
     * @param doubleField1 the value for tbl_audit_log.doubleField1
     *
     * @mbggenerated Sat Jan 30 17:19:35 CST 2016
     */
    public void setDoubleField1(Double doubleField1) {
        this.doubleField1 = doubleField1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_audit_log.doubleField2
     *
     * @return the value of tbl_audit_log.doubleField2
     *
     * @mbggenerated Sat Jan 30 17:19:35 CST 2016
     */
    public Double getDoubleField2() {
        return doubleField2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_audit_log.doubleField2
     *
     * @param doubleField2 the value for tbl_audit_log.doubleField2
     *
     * @mbggenerated Sat Jan 30 17:19:35 CST 2016
     */
    public void setDoubleField2(Double doubleField2) {
        this.doubleField2 = doubleField2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_audit_log.doubleField3
     *
     * @return the value of tbl_audit_log.doubleField3
     *
     * @mbggenerated Sat Jan 30 17:19:35 CST 2016
     */
    public Double getDoubleField3() {
        return doubleField3;
    }

    public void setDoubleField3(Double doubleField3) {
        this.doubleField3 = doubleField3;
    }

    public Double getDoubleField4() {
        return doubleField4;
    }

    public void setDoubleField4(Double doubleField4) {
        this.doubleField4 = doubleField4;
    }

    public Long getLongField1() {
        return longField1;
    }

    public void setLongField1(Long longField1) {
        this.longField1 = longField1;
    }

    public Long getLongField2() {
        return longField2;
    }

    public void setLongField2(Long longField2) {
        this.longField2 = longField2;
    }

    public Long getLongField3() {
        return longField3;
    }

    public void setLongField3(Long longField3) {
        this.longField3 = longField3;
    }

	public OperationType getOpTypeStr() {
		return opTypeStr;
	}

	public void setOpTypeStr(OperationType opTypeStr) {
		this.opTypeStr = opTypeStr;
	}

	public Integer getManagementUserId() {
		return managementUserId;
	}

	public void setManagementUserId(Integer managementUserId) {
		this.managementUserId = managementUserId;
	}

	public String getManagementUserName() {
		return managementUserName;
	}

	public void setManagementUserName(String managementUserName) {
		this.managementUserName = managementUserName;
	}

	public String getManagementLoginName() {
		return managementLoginName;
	}

	public void setManagementLoginName(String managementLoginName) {
		this.managementLoginName = managementLoginName;
	}
    
}